var set_div_1 = document.createElement('div');
set_div_1.className = 'container mt-3 align-content-center col-lg-7 card';
set_div_1.style = 'margin: 0 auto;background-color:rgba(255, 255, 255, 0.6);';
var set_body_1 = document.createElement('div');
set_body_1.className = 'card-body';
var set_text_1 = document.createElement('p');
set_text_1.className = 'card-text';
set_text_1.innerText = 'Hello World';
set_div_1.appendChild(set_body_1);
set_body_1.appendChild(set_text_1);
document.getElementById('add_card').appendChild(set_div_1);
var set_set_1_0 = document.createElement('a');
set_set_1_0.href = 'http://www.baidu.com';
set_set_1_0.innerText = 'Hello';
set_body_1.appendChild(set_set_1_0);
var set_set_1_1 = document.createElement('a');
set_set_1_1.href = 'http://cn.bing.com';
set_set_1_1.innerText = 'World';
set_body_1.appendChild(set_set_1_1);
